[package]
name = "shaku-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaku = "*"
anyhow = "*"
async-trait = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
